#!/usr/bin/env sh
#
# Autoformat Python with black.
# For details: blackbox --help

image='blackbox:latest'
docker build --tag $image - <<Dockerfile
FROM python:3
LABEL description="Autoformat Python code with Black"
LABEL maintainer="samkennerly@gmail.com"

RUN apt-get -y update
RUN pip install --upgrade pip && pip install black
WORKDIR /context

ENTRYPOINT ["black"]
Dockerfile
docker run --rm --tty --volume "$(pwd):/context" $image "$@"
